apiVersion: v1
kind: Secret
metadata:
  name: learn-api-secret
  namespace: lp
type: Opaque
data:
    ATLAS_URI: {{ .Values.database_url | b64enc | quote }}
    HASH_KEY: {{ .Values.hash_key | b64enc | quote }}
    JWT_SECRET_KEY: {{ .Values.jwt_secret_key | b64enc | quote }}